version: "3.8"

services:
  app:
    image: node:latest
    container_name: dope-shi-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "37849:37849"
    command: >
      sh -c "npm install && npm run dev"
